// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIC5VWdefEoGekME8C4CLSDUYsqpKd4uo',
    appId: '1:126248180118:web:406512f1918d8c5be3a5b7',
    messagingSenderId: '126248180118',
    projectId: 'todo-flutter-chatgpt',
    authDomain: 'todo-flutter-chatgpt.firebaseapp.com',
    storageBucket: 'todo-flutter-chatgpt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu2KyPom_dtteffTNw4rGnt1dCED0v2qM',
    appId: '1:126248180118:android:b21b64149beaf210e3a5b7',
    messagingSenderId: '126248180118',
    projectId: 'todo-flutter-chatgpt',
    storageBucket: 'todo-flutter-chatgpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz7ebtlhZ6l01wUxmpwQMJWS9H3Bcz2XA',
    appId: '1:126248180118:ios:b7c489554a41c3d5e3a5b7',
    messagingSenderId: '126248180118',
    projectId: 'todo-flutter-chatgpt',
    storageBucket: 'todo-flutter-chatgpt.appspot.com',
    iosClientId: '126248180118-ascr0h54d0nl18npv9vrhadhnbk55q57.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz7ebtlhZ6l01wUxmpwQMJWS9H3Bcz2XA',
    appId: '1:126248180118:ios:b7c489554a41c3d5e3a5b7',
    messagingSenderId: '126248180118',
    projectId: 'todo-flutter-chatgpt',
    storageBucket: 'todo-flutter-chatgpt.appspot.com',
    iosClientId: '126248180118-ascr0h54d0nl18npv9vrhadhnbk55q57.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
